# Generated by Django 5.1.3 on 2024-11-18 10:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_cats', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Breed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='spycat',
            name='breed',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spy_cats.breed'),
        ),
    ]
