# Generated by Django 5.1.3 on 2024-11-18 12:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spy_cats', '0002_breed_alter_spycat_breed'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='target',
            name='country',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spy_cats.country'),
        ),
    ]
